import { type PortfolioConfig } from "@/types/portfolio";

export const portfolioConfig: PortfolioConfig = {
  portfolioItems: [
    {
      id: "1",
      href: "/projects/",
      title: "PG Bison",
      description:
        "Introducing the PG Bison project, a multifunctional space designed to impress and cater to a wide range of needs. This unique location offers distinct areas that harmoniously combine to serve as a single, yet separable venue, perfect for filming and photography. Embracing the elements of fire, earth, air, and water, we create visually captivating spaces across the interior, exterior, and grounds, providing a holistic experience for sleeping, bathing, food preparation, and socializing. In this arid landscape, responsible water use is a priority. This versatile, rentable property promises a blend of sensory delights for unforgettable experiences.",
      designType: "Residential Design",
      previewImageUrl: "https://i.imgur.com/B3eqyAN.jpg",
      imageListUrls: [
        "https://i.imgur.com/B3eqyAN.png",
        "https://i.imgur.com/UCnKrEM.png",
        "https://i.imgur.com/OF4fCet.png",
        "https://i.imgur.com/k51FsAm.png",
        "https://i.imgur.com/g1FqwTK.png",
        "https://i.imgur.com/14DRDMd.png",
        "https://i.imgur.com/0mz3qQH.png",
        "https://i.imgur.com/rndzJhX.png",
        "https://i.imgur.com/t93PiSy.png",
        "https://i.imgur.com/q8ZRBA6.png",
        "https://i.imgur.com/2J8D8fn.png",
        "https://i.imgur.com/D0WFtcA.png",
        "https://i.imgur.com/PNrJAGU.png",
        "https://i.imgur.com/Bt89EHq.png",
      ],
    },
    {
      id: "2",
      href: "/projects/",
      title: "Skin Clinic",
      description:
        "South Africa's flourishing beer culture has seen a surge in microbreweries and brewpubs, now comprising a substantial portion of the market. Three passionate homebrewers aim to open a brewpub, crafting unique artisan blends with local ingredients. The project entails designing a brewpub with transparent microbrewery operations, establishing a distinctive brand identity, creating a menu with suggested food offerings, and designing unique beer bottle labels to complete the establishment's identity.",
      designType: "Healing Design",
      previewImageUrl: "https://i.imgur.com/LHinCeL.jpg",
      imageListUrls: [
        "https://i.imgur.com/LHinCeL.png",
        "https://i.imgur.com/99F8wrN.png",
        "https://i.imgur.com/wAB5RuM.png",
        "https://i.imgur.com/gRIP8AP.png",
        "https://i.imgur.com/oyapPSO.png",
        "https://i.imgur.com/orAlCOW.png",
        "https://i.imgur.com/IQ4nYX0.png",
        "https://i.imgur.com/9lUVo2r.png",
        "https://i.imgur.com/PMb0PAd.png",
        "https://i.imgur.com/KRnokYZ.png",
        "https://i.imgur.com/hFtz5m1.png",
        "https://i.imgur.com/7mUYqqT.png",
        "https://i.imgur.com/7TU21AN.png",
        "https://i.imgur.com/A7aUged.png",
        "https://i.imgur.com/dZGjnwY.png",
        "https://i.imgur.com/SZ6qmOn.png",
        "https://i.imgur.com/HUwyRru.png",
      ],
    },
    {
      id: "3",
      href: "/projects/",
      title: "Renovation",
      description:
        "This project involves the redesign of a house for Zara and Sam, where Zara faces mobility challenges due to a congenital joint condition. The design goal is to create an inclusive and functional living space that accommodates Zara's needs while reflecting their contemporary and minimalistic style. Key considerations include accessibility, safety, functionality, comfort, and style. The design ensures Zara can move comfortably using forearm crutches, prioritizing safety and functionality, all within a mindful budget. The focus is on making Zara comfortable while considering Sam's preferences.",
      designType: "Inclusive Home",
      previewImageUrl: "https://i.imgur.com/WcCROfm.jpg",
      imageListUrls: [
        "https://i.imgur.com/WcCROfm.png",
        "https://i.imgur.com/P8zgqQd.png",
        "https://i.imgur.com/eAu2Jqw.png",
        "https://i.imgur.com/aOvuhnZ.png",
        "https://i.imgur.com/ZsztLxh.png",
        "https://i.imgur.com/lMKBsSs.png",
        "https://i.imgur.com/YosuTUy.png",
        "https://i.imgur.com/i5EGjGO.png",
        "https://i.imgur.com/KPf478z.png",
        "https://i.imgur.com/oE4r9jy.png",
        "https://i.imgur.com/EfrQRvE.png",
      ],
    },
    {
      id: "4",
      href: "/projects/",
      title: "Brew Pub",
      description:
        "South Africa's flourishing beer culture has seen a surge in microbreweries and brewpubs, now comprising a substantial portion of the market. Three passionate homebrewers aim to open a brewpub, crafting unique artisan blends with local ingredients. The project entails designing a brewpub with transparent microbrewery operations, establishing a distinctive brand identity, creating a menu with suggested food offerings, and designing unique beer bottle labels to complete the establishment's identity.",
      designType: "Hospitality Design",
      previewImageUrl: "https://i.imgur.com/4Kpmdop.jpg",
      imageListUrls: [
        "https://i.imgur.com/4Kpmdop.png",
        "https://i.imgur.com/5ZmbGge.png",
        "https://i.imgur.com/G113kzT.png",
        "https://i.imgur.com/Mn29Ay0.png",
        "https://i.imgur.com/mNUeKcU.png",
        "https://i.imgur.com/0rdykMA.png",
        "https://i.imgur.com/EqYxm0o.png",
        "https://i.imgur.com/T2p8DyE.png",
        "https://i.imgur.com/CZV8JK7.png",
        "https://i.imgur.com/cX2B8Qr.png",
        "https://i.imgur.com/9TAHgru.png",
        "https://i.imgur.com/tOcHHTJ.png",
        "https://i.imgur.com/iUjk2NB.png",
        "https://i.imgur.com/ZgnOw5Z.png",
        "https://i.imgur.com/upKjEKK.png",
        "https://i.imgur.com/CT6CYTG.png",
        "https://i.imgur.com/ZgnOw5Z.png",
        "https://i.imgur.com/CoMmHir.png",
      ],
    },
    {
      id: "5",
      href: "/projects/",
      title: "Booking.com office",
      description:
        "Booking.com, a global online travel company, seeks an office design that aligns with their corporate culture of flexibility and openness. Their offices, found worldwide, celebrate travel and local culture, while promoting a healthy, productive workplace. The new office project must prioritize a healthy work environment and incorporate sustainable design elements. Colourful, playful, and inviting, the space encourages attendance while accommodating staff from various international offices, embodying Booking.com's unique identity and values.",
      designType: "Healthy Workplace",
      previewImageUrl: "https://i.imgur.com/CaBXx6L.jpg",
      imageListUrls: [
        "https://i.imgur.com/CaBXx6L.png",
        "https://i.imgur.com/H1x9I5r.png",
        "https://i.imgur.com/HI5n7sB.png",
        "https://i.imgur.com/4dxoeVX.png",
        "https://i.imgur.com/nWvi3ed.png",
        "https://i.imgur.com/jeldlcj.png",
        "https://i.imgur.com/9rJurZa.png",
        "https://i.imgur.com/OVru7qU.png",
        "https://i.imgur.com/XwYpyWm.png",
        "https://i.imgur.com/lQOWSAz.png",
        "https://i.imgur.com/LeZHFA4.png",
        "https://i.imgur.com/63I9ZFW.png",
        "https://i.imgur.com/vq3vpX7.png",
        "https://i.imgur.com/2H3BdFY.png",
        "https://i.imgur.com/EZTlBS5.png",
        "https://i.imgur.com/rsoa2Ko.png",
      ],
    },
  ],
};
